// Date: 15.08.2014 18:47:14
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package net.dimensionshiftinfectus.mod.model;

import net.dimensionshift.mod.api.DimensionShiftModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelArtificialMob extends DimensionShiftModelBase
{
  //fields
    ModelRenderer MainBody;
    ModelRenderer Body1;
    ModelRenderer Body2;
    ModelRenderer Body3;
    ModelRenderer Body4;
    ModelRenderer BodyTop;
  
  public ModelArtificialMob()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      MainBody = new ModelRenderer(this, 0, 0);
      MainBody.addBox(0F, 0F, 0F, 10, 10, 10);
      MainBody.setRotationPoint(-4F, 14F, -5F);
      MainBody.setTextureSize(64, 32);
      MainBody.mirror = true;
      setRotation(MainBody, 0F, 0F, 0F);
      Body1 = new ModelRenderer(this, 0, 20);
      Body1.addBox(0F, 0F, 0F, 5, 5, 8);
      Body1.setRotationPoint(-7F, 19F, -1F);
      Body1.setTextureSize(64, 32);
      Body1.mirror = true;
      setRotation(Body1, 0F, 0F, 0F);
      Body2 = new ModelRenderer(this, 0, 33);
      Body2.addBox(0F, 0F, 0F, 4, 7, 4);
      Body2.setRotationPoint(4F, 17F, -7F);
      Body2.setTextureSize(64, 32);
      Body2.mirror = true;
      setRotation(Body2, 0F, 0F, 0F);
      Body3 = new ModelRenderer(this, 0, 44);
      Body3.addBox(0F, 0F, 0F, 3, 2, 3);
      Body3.setRotationPoint(-3F, 22F, -7F);
      Body3.setTextureSize(64, 32);
      Body3.mirror = true;
      setRotation(Body3, 0F, 0F, 0F);
      Body4 = new ModelRenderer(this, 0, 49);
      Body4.addBox(0F, 0F, 0F, 3, 2, 3);
      Body4.setRotationPoint(5F, 22F, 4F);
      Body4.setTextureSize(64, 32);
      Body4.mirror = true;
      setRotation(Body4, 0F, 0F, 0F);
      BodyTop = new ModelRenderer(this, 40, 0);
      BodyTop.addBox(0F, 0F, 0F, 5, 4, 6);
      BodyTop.setRotationPoint(-1F, 10F, -4F);
      BodyTop.setTextureSize(64, 32);
      BodyTop.mirror = true;
      setRotation(BodyTop, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5){
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    MainBody.render(f5);
    Body1.render(f5);
    Body2.render(f5);
    Body3.render(f5);
    Body4.render(f5);
    BodyTop.render(f5);
  }
  
  public void render(float f){

	    MainBody.render(f);
	    Body1.render(f);
	    Body2.render(f);
	    Body3.render(f);
	    Body4.render(f);
	    BodyTop.render(f);
	  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z){
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity){
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
